matrix:
  include:
    - language: node_js
      node_js:
        - 10
        - 12
      cache: yarn
      before_install:
        - cd client

    - language: rust
      rust:
        - stable
        - beta
        - nightly
      cache: cargo
      before_install:
        - cd server
      before_script:
        - rustup component add rustfmt
        - rustup component add clippy
      script:
        - cargo fmt --all -- --check
        - cargo clippy
        - cargo build --verbose
        - cargo test --verbose

  allow_failures:
    - rust: nightly
  fast_finish: true

notifications:
  email:
    - sean@seanbailey.io
