[package]
name = "kauri"
version = "0.3.0"
authors = [
  "Sean Bailey <sean@seanbailey.io>",
  "Prajna Sariputra"
]
edition = "2018"

[dependencies]
zip = "0.5.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tiny_http = "0.6.2"
quick-xml = "0.15.0"
